export const db = {};
export const auth = {};
export const Timestamp = {};
export const COLLECTIONS = {};
export const collection = () => {};
export const query = () => {};
export const where = () => {};
export const doc = () => {};
export const getDoc = () => {};
export const getDocs = () => {};
export const setDoc = () => {};
export const updateDoc = () => {};
export const deleteDoc = () => {};
export const signInWithEmailAndPassword = () => {};
export const createUserWithEmailAndPassword = () => {};
export const sendPasswordResetEmail = () => {};
export const signOut = () => {};
export const onAuthStateChanged = () => {};
export const onSnapshot = () => {};
export const writeBatch = () => {};
export const arrayUnion = () => {};
export const arrayRemove = () => {};
export const serverTimestamp = () => {};
export const orderBy = () => {};
export const limit = () => {};
export const messaging = {};
export const getToken = () => {};
export const onMessage = () => {};
export const VAPID_KEY = '';
export const getMessaging = () => {};
export const app = {};
